theme: jekyll-theme-cayman
layout: page
title: "To do list"
permalink: https://github.com/LionRouge1/To_do_list/tree/main/dist
lsi: false
safe: true
source: [https://github.com/LionRouge1/To_do_list/tree/main/dist]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
